### ISSUE TITLE
Create test_resource

### ISSUE THREAD

**Issue by aberdean** [ole-vi/BeLL-Apps#13]
Should have a class ResourceTest.

Go to Library, and test functionalities.
- Add New Resource
- Request Resource
- Switch to Collection
- Add 2 Collections
- Add New Resource to Collection
- Merge Collections
- Delete Resource
- Delete Collections

**Comment by prmurphy** [comment]
Here's what I have so far https://github.com/prmurphy/BeLL-Apps/blob/dev/tests/test_resource.py
I doubt I will be able to finish it by tonight, and I have to go the the US embassy tomorrow so I'll be quite busy most of the day. If anyone wants to help out they are more than welcome to.

**Comment by aberdean** [comment]
Need fixing dropdown menu

**Comment by aberdean** [comment]
TODO: 
* Add another Collection
* Add New Resource to Collection
* Merge Collections
* Delete Resource
* Delete Collections

**Comment by waryhermit** [comment]
Fixed by #96
