### ISSUE TITLE
Create test_meetup.py

### ISSUE THREAD

**Issue by aberdean** [ole-vi/BeLL-Apps#15]
Should have a class MeetupTest.

- Start a New Meetup
- Recurring Meetup and Non-recurring Meetup
- Multi-day Meetup and Single-day Meetup
- Invite Member
- Cancel Meetup

**Comment by dogi** [comment]
thanks @waryhermit 

the missing info is:
- this issue is ready to be tested and
- the code is at https://github.com/ole-vi/BeLL-Apps/pull/36

**Comment by waryhermit** [comment]
I addressed the issues brought up in the meeting, and made a new pull request: https://github.com/ole-vi/BeLL-Apps/pull/44
