### ISSUE TITLE
Add explanation to documentation

### ISSUE THREAD

**Issue by mepda** [ole-vi/BeLL-Apps#2]
brainstorm docs:￼￼

https://docs.google.com/document/d/1orxRy3rtdno8IuIdJZhntLM7I6OQ8tTXwJxUN7RW6Ik/edit

**Comment by mepda** [comment]
started updating this the other day, but need more clarification into the concepts.

**Comment by mepda** [comment]
with help of Antonella, I was able to understand what was written in the google doc. Will continue to expand and refine it.

**Comment by aberdean** [comment]
Finished and published.
