### ISSUE TITLE
Find a way to have dropdown menus working on Sauce Labs

### ISSUE THREAD

**Issue by aberdean** [ole-vi/BeLL-Apps#38]
Any possible way to select an option from a dropdown menu seems to fail on Sauce Labs.
We need a solution for this problem before we can address some of the other issues.

**Comment by aberdean** [comment]
Issues affected - #10, #11, #13

**Comment by hikaruit15** [comment]
I think the reason is firefox 48. It is not friendly. Downgrade its version to 47 or upgrade to 49 or 50. It will work.

**Comment by hikaruit15** [comment]
open `base_case.py` in tests directory and change version of firefox
```python
if is_travis():
    USERNAME = os.environ['SAUCE_USERNAME']
    ACCESS_KEY = os.environ['SAUCE_ACCESS_KEY']
    sauce = SauceClient(USERNAME, ACCESS_KEY)
    browsers = [{"platform": "Windows 10",
                 "browserName": "firefox",
                 "version": "48",
```
