### ISSUE TITLE
Investigating codeceptJS framework

### ISSUE THREAD

**Issue by dogi** [ole-vi/BeLL-Apps#48]
http://codecept.io/

@aberdean did already parts of it with branch https://github.com/ole-vi/BeLL-Apps/tree/codeceptjs

more docu at http://open-learning-exchange.github.io/#!pages/automatedtestingcodeceptjs.md

**Comment by waryhermit** [comment]
@dogi I am going to try your Codecept branch locally on my computer today. After that, what else would you like done in regards to investigating codeceptjs?

**Comment by dogi** [comment]
@waryhermit and @hikaruit15 lets write kinda down where we are right now and where to we wanna go ...

**Comment by waryhermit** [comment]
@dogi Right now we have login working CodeceptJS, and it also logs in with cookies if the login function has already been used. In addition it cleans the database of configurations and sets the admin visits to zero, so the configurations page is displayed each testing session.

I have implemented the first part of [test survey](https://github.com/ole-vi/BeLL-Apps/issues/19) in CodeceptJS, and when @mappuji is done with his thesis stuff, he will start working on [test resource type](https://github.com/ole-vi/BeLL-Apps/issues/40)

@dogi Is there something in particular you would like explored in relation to CodeceptJS?

**Comment by dogi** [comment]
@waryhermit good quesiton ;)

@dogi thinks to redirect this question to everybody

@LeonardMensah @hikaruit15 @hannahgdubin @mappuji what do you think?

Possibile tasks:
- [x] since Login works (and cleans after himself @waryhermit please confirm) we could create PR
- [ ] maybe we should also disable standard login test ...
  - without removing that python code/file
- [ ] generally the big plan is to replace/compete with python test - so every python test is possible to be grabbed and made faster and/or better
- [ ] `add more ;)`

**Comment by waryhermit** [comment]
So if I understand correctly, the road map is kinda:

- Replace all python tests with codeceptjs tests on codecept branch
- Once all python tests are working in codeceptjs, make pull request to main branch
- Disable python tests in travis.yml but do not delete the files

Is that right?
