### ISSUE TITLE
create template for accessing couchdb by python

### ISSUE THREAD

**Issue by dogi** [ole-vi/BeLL-Apps#5]
examples at https://github.com/sente/BeLL-Apps-runner/tree/master/scripts/resources

**Comment by aberdean** [comment]
May be also helpful: https://github.com/djc/couchdb-python and https://pythonhosted.org/CouchDB/

**Comment by FanisGk** [comment]
PR: https://github.com/ole-vi/BeLL-Apps/pull/35
So far, it creates a member via python in couchdb and then tests login

**Comment by waryhermit** [comment]
This issue is not very specific, what functionality do we specifically require in order for this issue to be resolved?

**Comment by dogi** [comment]
@waryhermit right - not very specific - but my reasoning was mostly to point to `pycouch` library and examples to it

in the end we already kinda did this by creating an adding member function ...

- [ ] adding resource(s)
- [ ] change start language
- [ ] ...

**Comment by waryhermit** [comment]
There are good examples in my code for interacting with couchdb in https://github.com/ole-vi/BeLL-Apps/blob/dev/tests/codeceptjs-init.js 

We will create specific issues for situations where we need to modify couchdb directly
