### ISSUE TITLE
login save cookie go to other url by reloading it

### ISSUE THREAD

**Issue by dogi** [ole-vi/BeLL-Apps#6]
http://stackoverflow.com/questions/15058462/how-to-save-and-load-cookies-using-python-selenium-webdriver

**Comment by waryhermit** [comment]
@dogi I think if you specify a user folder for the webdriver it will automatically save the cookies as well.

**Comment by waryhermit** [comment]
@dogi

I am logging with saved cookies with CodeceptJS. Does that mean this issue is resolved?

**Comment by dogi** [comment]
@waryhermit can you point to the code and an example there ;)

50% closed ;)

- [ ] python
- [x] codeceptJS

**Comment by sente** [comment]
@dogi, @waryhermit -- 

saving cookies:

```python
import pickle
pickle.dump(driver.get_cookies() , open("cookies.pkl", "wb"))
```



loading cookies

```python
import pickle
for cookie in pickle.load(open("cookies.pkl", "rb")):
    driver.add_cookie(cookie)
```

**Comment by waryhermit** [comment]
Python tests will no longer be used soon.
