### ISSUE TITLE
Avoid using the `global` statement

### ISSUE THREAD

**Issue by dogi** [ole-vi/BeLL-Apps#62]
https://www.quantifiedcode.com/app/project/3e98b1b587c3474486279406edc6e341/diff/000a49daa8455ed7766041f314819fdbad2c66db/8733aa6e4d1b8d83498f8d3961a1e482cf343e20/issues?groups=code_patterns%3A1hX7eguD%3Af0

**Comment by empeje** [comment]
Interesting, I will take a look to this

**Comment by waryhermit** [comment]
In a few days I will have converted all tests to codeceptjs - I wouldn't work on this issue.
