### ISSUE TITLE
Make installer check multiple firefox reg keys

### ISSUE THREAD

**Issue by waryhermit** [ole-vi/BeLL-Apps#65]
Installer doesn't detect some FF installs.

**Comment by leomaxi** [comment]
Windows 10 path
HKEY_CURRENT_USER/SOFTWARE/Mozilla/Firefox

**Comment by waryhermit** [comment]
Just need @leonardmensah to make sure the installer doesn't ask him to install firefox anymore

**Comment by waryhermit** [comment]
https://github.com/ole-vi/BeLL-Apps/releases/download/try19/BellApp-19-setup.exe

**Comment by waryhermit** [comment]
This issue is fixed, but there is another one with curl
