### ISSUE TITLE
HTML5 Resources - convert “Hello Nurse” app

### ISSUE THREAD

**Issue by waryhermit** [ole-vi/BeLL-Apps#72]
Convert this to to html app
https://drive.google.com/open?id=0Bw7aA5bLT2P9Nk9SZTliSkRYYU0

**Comment by sarvanivadali** [comment]
Hi @waryhermit I have followed [these steps](http://open-learning-exchange.github.io/#!pages/htmlresources.md) and used Nurse application as an example. It seems to be working without any modification. Could you clarify what needs to be done?

**Comment by dogi** [comment]
thanks @sarvanivadali for asking

@Chris-Boe did also give the same problem a shot

which means we now have 2 solutions ...

http://vi.ole.org:5999/apps/_design/bell/MyApp/index.html#resources/pending

for checking out both of them ;)

**Comment by waryhermit** [comment]
@dogi So you are saying all that is left is for you to check them? Your post didn't really answer what needs to be done as far as I can tell.

**Comment by dogi** [comment]
@waryhermit I already checked them and there is some tiny difference ;)

**Comment by waryhermit** [comment]
@dogi So what do they need to fix???

**Comment by Chris-Boe** [comment]
@dogi , Both @sarvanivadali and I looked at our uploads today and they both work normally. Our processes in uploading them did not differ by much. Feel free to delete the resource labelled "Nurse Application" and we could close this issue

**Comment by dogi** [comment]
@Chris-Boe @sarvanivadali thanks - @leonardmensah and I 3 days ago did the same ;)
and fixed the one we better liked
