### ISSUE TITLE
Removed duplication of code #644 break python tests

### ISSUE THREAD

**Issue by dogi** [ole-vi/BeLL-Apps#77]
https://github.com/open-learning-exchange/BeLL-Apps/pull/644
this time all python tests fail
```
0.96s$ python -m unittest discover tests
EEEEEEEEEEEEEE
======================================================================
ERROR: test_feedback (base_case.FeedbackTest_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/open-learning-exchange/BeLL-Apps/tests/base_case.py", line 49, in setUp
    command_executor=sauce_url % (USERNAME, ACCESS_KEY))
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 92, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 179, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/selenium/webdriver/remote/remote_connection.py", line 415, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/selenium/webdriver/remote/remote_connection.py", line 479, in _request
    base64string = base64.b64encode('%s:%s' % (parsed_url.username, parsed_url.password))
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/base64.py", line 59, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
TypeError: a bytes-like object is required, not 'str'

...
```

https://gitter.im/open-learning-exchange/interns?at=58c0b4e7e961e53c7fbbefdc

**Comment by waryhermit** [comment]
it dying on this line: https://github.com/ole-vi/BeLL-Apps/blob/dev/tests/base_case.py#L48

**Comment by hikaruit15** [comment]
I don't think they just removed the duplication of code.
I read over the code and concern some codes.
In `CommunityRequestRow.js` file: 
line 12: `var centralNationUrl = App.Router.getCentralNationUrl();` 
line 39: ` "target": 'http://' + centralNationUrl + '/communityregistrationrequests',`

`centralNationUrl` is a local variable in if..else statement but line 39 is not in that scope.

**Comment by waryhermit** [comment]
I think there is a good chance this is because the version of selenium installed changed. If you go back to the last Travis CI build on `open-learning-exchange / BeLL-Apps` that worked it installed `selenium-3.0.2`, but on the ones that failed it installed `selenium-3.3.0`

I suggest we try forcing it to install the old version to test this idea. If it does fix it we can keep it as a fix temporary until we figure out what we need to change to work with the new version.

**Comment by waryhermit** [comment]
See also: https://github.com/SeleniumHQ/selenium/issues/3622

I noticed when they tired to reproduce the issue they used python 3.6 and they didn't have the problem

**Comment by waryhermit** [comment]
This issue needs to be revisited when the next selenium package for Python is released, as they have fixed the issue: SeleniumHQ/selenium#3622

**Comment by dogi** [comment]
awesome

**Comment by waryhermit** [comment]
The patch was released:

https://github.com/SeleniumHQ/selenium/blob/master/py/CHANGES
https://pypi.python.org/pypi/selenium

we can try switching back to not specifying the version.

**Comment by waryhermit** [comment]
We are phasing out python tests anyway
