### ISSUE TITLE
NPM error in Travis build

### ISSUE THREAD

**Issue by empeje** [ole-vi/BeLL-Apps#83]
@dogi found a problem with npm in travis.

You can see all the Travis log here https://travis-ci.org/open-learning-exchange/BeLL-Apps/builds
The problem is particularly in these build:

1. https://travis-ci.org/open-learning-exchange/BeLL-Apps/builds/212871860
2. https://travis-ci.org/open-learning-exchange/BeLL-Apps/builds/212886784
3. https://travis-ci.org/open-learning-exchange/BeLL-Apps/builds/212918271
4. https://travis-ci.org/open-learning-exchange/BeLL-Apps/builds/212930166

I think the main problem is in the npm's access to the internet connection or network.

**Comment by waryhermit** [comment]
Since this for the most part resolved it self, I would redirect our efforts into preventing this kind problem in the future: https://github.com/ole-vi/BeLL-Apps/issues/84
