### ISSUE TITLE
Indonesian Translation Vote

### ISSUE THREAD

**Issue by empeje** [ole-vi/BeLL-Apps#94]
Hi Team,

I have translated current text assets of BeLL for Bahasa Indonesia (Indonesian) at Crowdin. Next step is to have a vote from others who knows the language.

I know that only few people, know this language currently in this community, but this issue is a place to get started once others who knows some Indonesian to verified my translation.

Here are the link for [OLE-Crowdin](https://crowdin.com/project/open-learning-exchange/invite)

**Comment by dogi** [comment]
@mappuji very awesome
