### ISSUE TITLE
Test vagrant auto-start task on windows.

### ISSUE THREAD

**Issue by waryhermit** [ole-vi/BeLL-Apps#97]
For everyone with a windows machine:

- Find and delete any existing tasks created by the install script.
- Run the following commands in an Administrator power-shell window:
```
$repo = "ole--vagrant-vi"
$Stt = New-ScheduledTaskTrigger -AtLogon
$Sta = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-ExecutionPolicy Bypass  $HOME\$repo\windows\vagrantup.ps1"
Register-ScheduledTask TestVagrantUp1 -Action $Sta -Trigger $Stt
```

- Restart your computer and check if vagrant started by running `vagrant global-status` in the correct directory.

Let me know if it works / does not work.

**Comment by kylemathias** [comment]
Got this when i ran it. windows 10 pro
![image](https://cloud.githubusercontent.com/assets/26488295/24675253/530921d4-1933-11e7-9820-0b5aaaf6c2b3.png)

**Comment by waryhermit** [comment]
@kylemathias I said **power-shell** window 😄

**Comment by Loshi93** [comment]
@waryhermit Got this when I ran in Windows 8
![image](https://cloud.githubusercontent.com/assets/24893117/24677203/d0f2f118-193a-11e7-9c77-1ebb4c659d70.png)

**Comment by waryhermit** [comment]
@Loshma93 OK, did vagrant automatically start for you when you restarted?

**Comment by Loshi93** [comment]
@waryhermit When I enabled "vagrant up" in correct folder screen appears like this:
![image](https://cloud.githubusercontent.com/assets/24893117/24678568/dd684cfe-193f-11e7-8297-e839a0ccbf7e.png)

**Comment by waryhermit** [comment]
@Loshma93 The script I had you run creates a task in the windows task scheduler that runs `vagrant up` for you every time you reboot logon to your user account. I want to know if it works for you - so when you restart sometime check by running `vagrant global-status`. If vagrant has been started and you don't need to do `vagrant up` by yourself my script works.

**Comment by Loshi93** [comment]
@waryhermit I restarted my laptop and checked vagrant global-status and it is running
![image](https://cloud.githubusercontent.com/assets/24893117/24680669/aeabfa9e-1946-11e7-9bf0-5894e1bd68c0.png)

**Comment by Loshi93** [comment]
@waryhermit But when I open Bell-Apps it says "problem loading page"
![image](https://cloud.githubusercontent.com/assets/24893117/24680720/e40cd32a-1946-11e7-95e5-ffc4f6eb2d66.png)

**Comment by waryhermit** [comment]
Huh, how long did you wait? Maybe the vm was still booting?

**Comment by Loshi93** [comment]
@waryhermit It's working now
![image](https://cloud.githubusercontent.com/assets/24893117/24682742/32cd493c-1950-11e7-943f-96dab0fa9adb.png)

**Comment by kylemathias** [comment]
@waryhermit lol, never used powershell =P.
![image](https://cloud.githubusercontent.com/assets/26488295/24714956/d9ba6a02-19de-11e7-9ca5-5d3623852beb.png)

ill restart and try MyBell. BTW my vagrant status has always said "Up" when i check its status, but when i run MyBell it gives the 404. I Usually have to tell it "vagrant up" for it to work.

**Comment by kylemathias** [comment]
I restarted it and it works.
![image](https://cloud.githubusercontent.com/assets/26488295/24715358/ea121552-19df-11e7-8f24-fc94812ef94c.png)

**Comment by paulbert** [comment]
Worked for me on Windows 10 Home.

**Comment by Ebuka-Chibueze** [comment]
Worked for me on Windows 10 as well.

**Comment by Ebuka-Chibueze** [comment]
@waryhermit Btw I was kinda confused by
> - Restart your computer and check if vagrant started by running `vagrant up` in the correct directory.

Wouldn't it make more sense to tell us to run `vagrant global-status`?

**Comment by waryhermit** [comment]
@Ebuka-Chibueze It was a typo, thanks for catching it. I wonder why it didn't work on @sarvanivadali computer, it seems to be working for other people...

**Comment by dogi** [comment]
@waryhermit as we decided your change is a go

**Comment by waryhermit** [comment]
@dogi see https://github.com/dogi/ole--vagrant-vi/pull/22/files

**Comment by dogi** [comment]
@waryhermit https://github.com/dogi/ole--vagrant-vi/commit/d85e31512fff8629d07a289f0ce2f1c19c2ed227

**Comment by dogi** [comment]
it is live now ;)

**Comment by waryhermit** [comment]
Its live
